import 'dart:async';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import '../models/content_analysis_result.dart';
import '../utils/app_logger.dart';
import 'content_analyzer.dart';

/// An alert generated by the safety analysis pipeline.
class Alert {
  final ContentAnalysisResult result;
  final String description;
  final DateTime timestamp;

  const Alert({
    required this.result,
    required this.description,
    required this.timestamp,
  });
}

/// Subscribes to [ContentAnalyzer.analysisStream] and fires alerts
/// when [ContentAnalysisResult.riskScore] >= 70.
///
/// Acts as Layer 4 in the pipeline — consumers (parent dashboard UI)
/// subscribe to [alertStream].
class AlertService {
  static const int _riskThreshold = 70;

  final ContentAnalyzer _analyzer;

  AlertService(this._analyzer);

  final _alertController = StreamController<Alert>.broadcast();
  Stream<Alert> get alertStream => _alertController.stream;

  StreamSubscription<AnalysisEvent>? _sub;
  bool _running = false;

  final _notifs = FlutterLocalNotificationsPlugin();
  bool _notifsInitialized = false;

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  Future<void> start() async {
    if (_running) return;
    _running = true;

    await _initNotifications();

    AppLogger.log('[AlertService] Started — watching for riskScore >= $_riskThreshold');
    _sub = _analyzer.analysisStream.listen(_onAnalysisEvent);
  }

  void stop() {
    _running = false;
    _sub?.cancel();
    _sub = null;
    AppLogger.log('[AlertService] Stopped');
  }

  void dispose() {
    stop();
    _alertController.close();
  }

  // ── Handler ───────────────────────────────────────────────────────────────

  void _onAnalysisEvent(AnalysisEvent event) {
    final score = event.result.riskScore;
    AppLogger.log('[AlertService] Received event — riskScore=$score');

    if (score < _riskThreshold) return;

    AppLogger.log('[AlertService] 🚨 HIGH RISK ($score%) — firing alert');

    final alert = Alert(
      result: event.result,
      description: event.description,
      timestamp: event.timestamp,
    );

    // Emit to UI stream
    if (!_alertController.isClosed) {
      _alertController.add(alert);
    }

    // Show local notification
    _showNotification(alert);
  }

  // ── Notifications ─────────────────────────────────────────────────────────

  Future<void> _initNotifications() async {
    if (_notifsInitialized) return;
    const android = AndroidInitializationSettings('@mipmap/ic_launcher');
    await _notifs.initialize(const InitializationSettings(android: android));
    _notifsInitialized = true;
    AppLogger.log('[AlertService] Notifications initialized');
  }

  Future<void> _showNotification(Alert alert) async {
    try {
      await _notifs.show(
        DateTime.now().millisecondsSinceEpoch ~/ 1000, // unique-ish ID
        '🚨 Safety Alert: ${alert.result.riskScore}% Risk',
        alert.result.summary,
        const NotificationDetails(
          android: AndroidNotificationDetails(
            'alerts_channel',
            'Safety Alerts',
            channelDescription: 'High-risk content safety alerts',
            importance: Importance.high,
            priority: Priority.high,
          ),
        ),
      );
    } catch (e) {
      AppLogger.logError('[AlertService] Notification error', e);
    }
  }
}
